version: '3.8'

services:
    app:
        container_name: app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
        depends_on:
            - minio
            - redis
    minio:
        image: minio/minio:latest
        container_name: minio
        restart: always
        env_file:
            - .env
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        volumes:
          - ./data/minio:/data
        ports:
          - "9000:9000"
          - "9001:9001"
        command: server /data --console-address ":9001"
    redis:
        image: redis:7.0-alpine
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
    minio_data:
